### ISSUE TITLE
WeiDU_TRA delimiter

### ISSUE THREAD

**Issue by MikeX1234** [Argent77/NotePad_PlusPlus_WeiDU#2]
It' more of a question:
If you have a ^ sign in the tra file, all the rest of the data are shown in red.
I remove ^ and ^- from the xml delimiter line and everything looks ok:

`            <Keywords name="Delimiters">00~ 01 02~ 03[ 04 05] 06&quot; 07 08&quot; 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23</Keywords>
`
Was there a reason they where in there or was it just in oversight?

Thanks, I really appreciate all your work!

**Comment by Argent77** [comment]
It is possible to [colorize](https://gibberlings3.github.io/iesdp/appendices/charactercreation.htm) portions of a string in EE games. `^` and `^-` are delimiters for the colorized range. You can safely remove these delimiters from the xml definition if you don't need it.

**Comment by MikeX1234** [comment]
Ok, thank you.
